# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS-15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4
      with:
        submodules: true

    # Runs a set of commands using the runners shell
    - name: Run mac tests
      run:
        xcodebuild
          -scheme audio
          -configuration debug
          -destination 'platform=macOS'
          clean test
    - name: Run iOS tests
      run:
        xcodebuild
          -scheme audio
          -configuration debug
          -destination 'platform=iOS Simulator,name=iPhone 16'
          clean build
